
theme: jekyll-theme-cayman
title: Hardware Aware Efficient Training
description: Workshop at ICLR 2021

navigation:
  Home: "/"
  Call for Papers: "/cfp"
  Organisers: "/organisers"
  Speakers: "/speakers"
  Schedule: "/schedule"

markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true


